"""add field to users to profile table

Revision ID: 0653057ebf69
Revises: 3cce64b6b19c
Create Date: 2023-02-17 16:50:41.967860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0653057ebf69'
down_revision = '3cce64b6b19c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=12), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False, default=False),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.Column('security_code', sa.String(length=5), nullable=True),
    sa.Column('sex', sa.String(length=1), nullable=True),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.Column('alias', sa.String(length=30), nullable=True),
    sa.Column('job', sa.String(length=120), nullable=True),
    sa.Column('city_id', sa.Integer(), nullable=True, comment='City to which the player belongs'),
    sa.Column('photo', sa.String(length=255), nullable=True),
    sa.Column('elo', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['resources.city.id'], ),
    sa.ForeignKeyConstraint(['country_id'], ['resources.country.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username'),
    schema='enterprise'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users', schema='enterprise')
    # ### end Alembic commands ###
