"""add profile followers table

Revision ID: 2458f7de0b07
Revises: 77f7ae277e28
Create Date: 2023-07-27 15:50:13.615350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2458f7de0b07'
down_revision = '77f7ae277e28'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile_followers',
    sa.Column('profile_id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('profile_follow_id', sa.String(), nullable=False),
    sa.Column('username_follow', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['profile_follow_id'], ['enterprise.profile_member.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['enterprise.profile_member.id'], ),
    sa.PrimaryKeyConstraint('profile_id', 'profile_follow_id'),
    schema='enterprise'
    )
    

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile_followers', schema='enterprise')
        # ### end Alembic commands ###
