"""add invitations table

Revision ID: 272e90aab004
Revises: 4a618d19e739
Create Date: 2023-05-19 13:55:45.079382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '272e90aab004'
down_revision = '4a618d19e739'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table('invitations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tourney_id', sa.String(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=False),
    sa.Column('status_name', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_date', sa.Date(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=False),
    sa.Column('updated_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['enterprise.users.username'], ),
    sa.ForeignKeyConstraint(['status_name'], ['resources.entities_status.name'], ),
    sa.ForeignKeyConstraint(['tourney_id'], ['events.tourney.id'], ),
    sa.ForeignKeyConstraint(['user_name'], ['enterprise.users.username'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='events'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invitations', schema='events')
    # ### end Alembic commands ###
