"""add domino boletus table

Revision ID: 34e5fbf2db14
Revises: a6806535febf
Create Date: 2023-10-14 23:21:15.106295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34e5fbf2db14'
down_revision = 'a6806535febf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domino_boletus',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tourney_id', sa.String(), nullable=False),
    sa.Column('round_id', sa.String(), nullable=False),
    sa.Column('table_id', sa.String(), nullable=False),
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('is_winner', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['events.players.id'], ),
    sa.ForeignKeyConstraint(['round_id'], ['events.domino_rounds.id'], ),
    sa.ForeignKeyConstraint(['table_id'], ['events.domino_tables.id'], ),
    sa.ForeignKeyConstraint(['tourney_id'], ['events.tourney.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='events'
    )
    op.create_table('domino_scale',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tourney_id', sa.String(), nullable=False),
    sa.Column('round_id', sa.String(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('position_number', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['events.players.id'], ),
    sa.ForeignKeyConstraint(['round_id'], ['events.domino_rounds.id'], ),
    sa.ForeignKeyConstraint(['tourney_id'], ['events.tourney.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='events'
    )
    op.create_table('domino_boletus_position',
    sa.Column('boletus_id', sa.String(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('single_profile_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['boletus_id'], ['events.domino_boletus.id'], ),
    sa.PrimaryKeyConstraint('boletus_id', 'position_id'),
    schema='events'
    )
    op.create_table('domino_data',
    sa.Column('boletus_id', sa.String(), nullable=False),
    sa.Column('data_number', sa.Integer(), nullable=False),
    sa.Column('single_profile_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['boletus_id'], ['events.domino_boletus.id'], ),
    sa.PrimaryKeyConstraint('boletus_id'),
    schema='events'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('domino_data', schema='events')
    op.drop_table('domino_boletus_position', schema='events')
    op.drop_table('domino_scale', schema='events')
    op.drop_table('domino_boletus', schema='events')
    # ### end Alembic commands ###
