"""add domino boletus posi all table

Revision ID: 388f553b4347
Revises: 80a1fa761ed2
Create Date: 2023-10-22 00:18:06.960257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '388f553b4347'
down_revision = '80a1fa761ed2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domino_boletus',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tourney_id', sa.String(), nullable=False),
    sa.Column('round_id', sa.String(), nullable=False),
    sa.Column('table_id', sa.String(), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['round_id'], ['events.domino_rounds.id'], ),
    sa.ForeignKeyConstraint(['table_id'], ['events.domino_tables.id'], ),
    sa.ForeignKeyConstraint(['tourney_id'], ['events.tourney.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='events'
    )
    op.create_table('domino_tables_files',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('table_id', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_ready', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['table_id'], ['events.domino_tables.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='events'
    )
    op.create_table('domino_boletus_position',
    sa.Column('boletus_id', sa.String(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('single_profile_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['boletus_id'], ['events.domino_boletus.id'], ),
    sa.PrimaryKeyConstraint('boletus_id', 'position_id'),
    schema='events'
    )
    op.create_table('domino_rounds_pairs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tourney_id', sa.String(), nullable=True),
    sa.Column('round_id', sa.String(), nullable=False),
    sa.Column('one_player_id', sa.String(), nullable=True),
    sa.Column('two_player_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('profile_type', sa.String(), nullable=False),
    sa.Column('player_id', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_date', sa.Date(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=False),
    sa.Column('updated_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['enterprise.users.username'], ),
    sa.ForeignKeyConstraint(['one_player_id'], ['enterprise.profile_member.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['events.players.id'], ),
    sa.ForeignKeyConstraint(['round_id'], ['events.domino_rounds.id'], ),
    sa.ForeignKeyConstraint(['tourney_id'], ['events.tourney.id'], ),
    sa.ForeignKeyConstraint(['two_player_id'], ['enterprise.profile_member.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['enterprise.users.username'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='events'
    )
    op.create_table('domino_rounds_scale',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tourney_id', sa.String(), nullable=False),
    sa.Column('round_id', sa.String(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('position_number', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.String(), nullable=True),
    sa.Column('elo', sa.Integer(), nullable=True),
    sa.Column('elo_variable', sa.Integer(), nullable=True),
    sa.Column('games_played', sa.Integer(), nullable=True),
    sa.Column('games_won', sa.Integer(), nullable=True),
    sa.Column('games_lost', sa.Integer(), nullable=True),
    sa.Column('points_positive', sa.Integer(), nullable=True),
    sa.Column('points_negative', sa.Integer(), nullable=True),
    sa.Column('points_difference', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['events.players.id'], ),
    sa.ForeignKeyConstraint(['round_id'], ['events.domino_rounds.id'], ),
    sa.ForeignKeyConstraint(['tourney_id'], ['events.tourney.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='events'
    )
    op.create_table('domino_boletus_pairs',
    sa.Column('boletus_id', sa.String(), nullable=False),
    sa.Column('pairs_id', sa.String(), nullable=False),
    sa.Column('is_initiator', sa.Boolean(), nullable=False),
    sa.Column('is_winner', sa.Boolean(), nullable=False),
    sa.Column('number_points', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['boletus_id'], ['events.domino_boletus.id'], ),
    sa.ForeignKeyConstraint(['pairs_id'], ['events.domino_rounds_pairs.id'], ),
    sa.PrimaryKeyConstraint('boletus_id', 'pairs_id'),
    schema='events'
    )
    op.create_table('domino_boletus_data',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('boletus_id', sa.String(), nullable=True),
    sa.Column('data_number', sa.Integer(), nullable=False),
    sa.Column('win_pair_id', sa.String(), nullable=True),
    sa.Column('win_by_points', sa.Boolean(), nullable=False),
    sa.Column('win_by_time', sa.Boolean(), nullable=False),
    sa.Column('number_points', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['boletus_id'], ['events.domino_boletus.id'], ),
    sa.ForeignKeyConstraint(['win_pair_id'], ['events.domino_rounds_pairs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='events'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('domino_data', schema='events')
    op.drop_table('domino_boletus_pairs', schema='events')
    op.drop_table('domino_scale', schema='events')
    op.drop_table('domino_rounds_pairs', schema='events')
    op.drop_table('domino_boletus_position', schema='events')
    op.drop_table('domino_tables_files', schema='events')
    op.drop_table('domino_boletus', schema='events')
    # ### end Alembic commands ###
