"""add eventrole table

Revision ID: 392d284eb9dc
Revises: ba374531ec5c
Create Date: 2023-05-12 13:10:54.832806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '392d284eb9dc'
down_revision = 'ba374531ec5c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table('event_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='resources'
    )
    
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_roles', schema='resources')
    # ### end Alembic commands ###
