"""add federations table

Revision ID: 3db602c07bae
Revises: 7364a0a54759
Create Date: 2024-02-22 11:16:12.221861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3db602c07bae'
down_revision = '7364a0a54759'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('federations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('logo', sa.String(), nullable=True),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['resources.city.id'], ),
    sa.ForeignKeyConstraint(['country_id'], ['resources.country.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='federations'
    )
    op.create_table('clubs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('logo', sa.String(), nullable=True),
    sa.Column('federation_id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['resources.city.id'], ),
    sa.ForeignKeyConstraint(['country_id'], ['resources.country.id'], ),
    sa.ForeignKeyConstraint(['federation_id'], ['federations.federations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='federations'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_table('clubs', schema='federations')
    op.drop_table('federations', schema='federations')
    # ### end Alembic commands ###
