"""upadte field to users table

Revision ID: 445feac9cd97
Revises: 475116fa48c4
Create Date: 2023-02-16 09:08:54.196752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '445feac9cd97'
down_revision = '475116fa48c4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=8), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('pais_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pais_id'], ['configuracion.pais.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('username'),
    schema='enterprise'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users', schema='enterprise')
    # ### end Alembic commands ###
