"""add users table

Revision ID: 475116fa48c4
Revises: 89e989fe5513
Create Date: 2023-02-10 10:22:21.084024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '475116fa48c4'
down_revision = '89e989fe5513'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('pais',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('nombre', sa.String(length=120), nullable=False),
    # sa.Column('is_active', sa.Boolean(), nullable=False),
    # sa.PrimaryKeyConstraint('id'),
    # schema='configuracion'
    # )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('fullname', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=8), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('pais_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pais_id'], ['configuracion.pais.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('username'),
    schema='enterprise'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users', schema='enterprise')
    # op.drop_table('pais', schema='configuracion')
    # ### end Alembic commands ###
