"""add user_eventrole table

Revision ID: 4a618d19e739
Revises: 392d284eb9dc
Create Date: 2023-05-12 17:01:31.328821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a618d19e739'
down_revision = '392d284eb9dc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_eventroles',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('eventrol_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['enterprise.users.username'], ),
    sa.ForeignKeyConstraint(['eventrol_id'], ['resources.event_roles.id'], ),
    sa.PrimaryKeyConstraint('username', 'eventrol_id'),
    schema='enterprise'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_eventroles', schema='enterprise')
    # ### end Alembic commands ###
