"""refactory tables

Revision ID: 63f83f2a95c6
Revises: afda3624e06a
Create Date: 2023-12-28 16:53:05.347271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63f83f2a95c6'
down_revision = 'afda3624e06a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tourney',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('modality', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('close_date', sa.Date(), nullable=False),
    sa.Column('amount_tables', sa.Integer(), nullable=False),
    sa.Column('amount_smart_tables', sa.Integer(), nullable=False),
    sa.Column('amount_rounds', sa.Integer(), nullable=False),
    sa.Column('number_points_to_win', sa.Integer(), nullable=False),
    sa.Column('time_to_win', sa.Integer(), nullable=False),
    sa.Column('game_system', sa.String(length=120), nullable=False),
    sa.Column('lottery_type', sa.String(length=120), nullable=False),
    sa.Column('penalties_limit', sa.Integer(), nullable=False),
    sa.Column('image', sa.Text(), nullable=True),
    sa.Column('use_bonus', sa.Boolean(), nullable=False),
    sa.Column('use_segmentation', sa.Boolean(), nullable=False),
    sa.Column('amount_bonus_tables', sa.Integer(), nullable=False),
    sa.Column('amount_bonus_points', sa.Integer(), nullable=False),
    sa.Column('number_bonus_round', sa.Integer(), nullable=False),
    sa.Column('elo_min', sa.Float(), nullable=False),
    sa.Column('elo_max', sa.Float(), nullable=False),
    sa.Column('profile_id', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_date', sa.Date(), nullable=False),
    sa.Column('updated_date', sa.Date(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['enterprise.users.username'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.events.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['enterprise.profile_member.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['enterprise.users.username'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='events'
    )
    op.create_table('domino_categories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tourney_id', sa.String(), nullable=False),
    sa.Column('category_number', sa.String(length=100), nullable=False),
    sa.Column('position_number', sa.Integer(), nullable=False),
    sa.Column('elo_min', sa.Float(), nullable=False),
    sa.Column('elo_max', sa.Float(), nullable=False),
    sa.Column('amount_players', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tourney_id'], ['events.tourney.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='events'
    )
    op.create_table('domino_rounds',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tourney_id', sa.String(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('close_date', sa.DateTime(), nullable=False),
    sa.Column('is_first', sa.Boolean(), nullable=False),
    sa.Column('is_last', sa.Boolean(), nullable=False),
    sa.Column('use_segmentation', sa.Boolean(), nullable=False),
    sa.Column('use_bonus', sa.Boolean(), nullable=False),
    sa.Column('amount_bonus_tables', sa.Integer(), nullable=False),
    sa.Column('amount_bonus_points', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_date', sa.Date(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('updated_date', sa.Date(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['enterprise.users.username'], ),
    sa.ForeignKeyConstraint(['status_id'], ['resources.entities_status.id'], ),
    sa.ForeignKeyConstraint(['tourney_id'], ['events.tourney.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['enterprise.users.username'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='events'
    )
    op.create_table('domino_tables',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tourney_id', sa.String(), nullable=False),
    sa.Column('table_number', sa.Integer(), nullable=False),
    sa.Column('is_smart', sa.Boolean(), nullable=False),
    sa.Column('amount_bonus', sa.Integer(), nullable=False),
    sa.Column('image', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_date', sa.Date(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('updated_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['enterprise.users.username'], ),
    sa.ForeignKeyConstraint(['tourney_id'], ['events.tourney.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['enterprise.users.username'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='events'
    )
    op.create_table('domino_boletus',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tourney_id', sa.String(), nullable=False),
    sa.Column('round_id', sa.String(), nullable=False),
    sa.Column('table_id', sa.String(), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['round_id'], ['events.domino_rounds.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['resources.entities_status.id'], ),
    sa.ForeignKeyConstraint(['table_id'], ['events.domino_tables.id'], ),
    sa.ForeignKeyConstraint(['tourney_id'], ['events.tourney.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='events'
    )
    op.create_table('domino_tables_files',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('table_id', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_ready', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['table_id'], ['events.domino_tables.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='events'
    )
    op.create_table('players',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tourney_id', sa.String(), nullable=False),
    sa.Column('profile_id', sa.String(), nullable=False),
    sa.Column('invitation_id', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_date', sa.Date(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=False),
    sa.Column('updated_date', sa.Date(), nullable=False),
    sa.Column('elo', sa.Float(), nullable=True),
    sa.Column('level', sa.String(length=60), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['enterprise.users.username'], ),
    sa.ForeignKeyConstraint(['invitation_id'], ['events.invitations.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['enterprise.profile_member.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['resources.entities_status.id'], ),
    sa.ForeignKeyConstraint(['tourney_id'], ['events.tourney.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['enterprise.users.username'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='events'
    )
    op.create_table('referees',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tourney_id', sa.String(), nullable=False),
    sa.Column('profile_id', sa.String(), nullable=False),
    sa.Column('invitation_id', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_date', sa.Date(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=False),
    sa.Column('updated_date', sa.Date(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['enterprise.users.username'], ),
    sa.ForeignKeyConstraint(['invitation_id'], ['events.invitations.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['enterprise.profile_member.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['resources.entities_status.id'], ),
    sa.ForeignKeyConstraint(['tourney_id'], ['events.tourney.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['enterprise.users.username'], ),
    sa.PrimaryKeyConstraint('id', 'tourney_id'),
    schema='events'
    )
    op.create_table('domino_boletus_position',
    sa.Column('boletus_id', sa.String(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('single_profile_id', sa.String(), nullable=True),
    sa.Column('scale_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['boletus_id'], ['events.domino_boletus.id'], ),
    sa.PrimaryKeyConstraint('boletus_id', 'position_id'),
    schema='events'
    )
    op.create_table('domino_rounds_pairs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tourney_id', sa.String(), nullable=True),
    sa.Column('round_id', sa.String(), nullable=False),
    sa.Column('position_number', sa.Integer(), nullable=False),
    sa.Column('one_player_id', sa.String(), nullable=True),
    sa.Column('two_player_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('profile_type', sa.String(), nullable=False),
    sa.Column('player_id', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_date', sa.Date(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=False),
    sa.Column('updated_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('scale_number_one_player', sa.Integer(), nullable=True),
    sa.Column('scale_number_two_player', sa.Integer(), nullable=True),
    sa.Column('scale_id_one_player', sa.String(), nullable=True),
    sa.Column('scale_id_two_player', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['enterprise.users.username'], ),
    sa.ForeignKeyConstraint(['one_player_id'], ['enterprise.profile_member.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['events.players.id'], ),
    sa.ForeignKeyConstraint(['round_id'], ['events.domino_rounds.id'], ),
    sa.ForeignKeyConstraint(['tourney_id'], ['events.tourney.id'], ),
    sa.ForeignKeyConstraint(['two_player_id'], ['enterprise.profile_member.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['enterprise.users.username'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='events'
    )
    op.create_table('domino_rounds_scale',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tourney_id', sa.String(), nullable=False),
    sa.Column('round_id', sa.String(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('position_number', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.String(), nullable=True),
    sa.Column('elo', sa.Float(), nullable=True),
    sa.Column('elo_variable', sa.Float(), nullable=True),
    sa.Column('games_played', sa.Integer(), nullable=True),
    sa.Column('games_won', sa.Integer(), nullable=True),
    sa.Column('games_lost', sa.Integer(), nullable=True),
    sa.Column('points_positive', sa.Integer(), nullable=True),
    sa.Column('points_negative', sa.Integer(), nullable=True),
    sa.Column('points_difference', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('category_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['events.players.id'], ),
    sa.ForeignKeyConstraint(['round_id'], ['events.domino_rounds.id'], ),
    sa.ForeignKeyConstraint(['tourney_id'], ['events.tourney.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='events'
    )
    op.create_table('trace_lottery_manual',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tourney_id', sa.String(), nullable=True),
    sa.Column('modality', sa.String(length=30), nullable=False),
    sa.Column('position_number', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['events.players.id'], ),
    sa.ForeignKeyConstraint(['tourney_id'], ['events.tourney.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='events'
    )
    op.create_table('domino_boletus_data',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('boletus_id', sa.String(), nullable=True),
    sa.Column('data_number', sa.Integer(), nullable=False),
    sa.Column('win_pair_id', sa.String(), nullable=True),
    sa.Column('win_by_points', sa.Boolean(), nullable=False),
    sa.Column('win_by_time', sa.Boolean(), nullable=False),
    sa.Column('number_points', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['boletus_id'], ['events.domino_boletus.id'], ),
    sa.ForeignKeyConstraint(['win_pair_id'], ['events.domino_rounds_pairs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='events'
    )
    op.create_table('domino_boletus_pairs',
    sa.Column('boletus_id', sa.String(), nullable=False),
    sa.Column('pairs_id', sa.String(), nullable=False),
    sa.Column('is_initiator', sa.Boolean(), nullable=False),
    sa.Column('is_winner', sa.Boolean(), nullable=False),
    sa.Column('positive_points', sa.Integer(), nullable=True),
    sa.Column('negative_points', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['boletus_id'], ['events.domino_boletus.id'], ),
    sa.ForeignKeyConstraint(['pairs_id'], ['events.domino_rounds_pairs.id'], ),
    sa.PrimaryKeyConstraint('boletus_id', 'pairs_id'),
    schema='events'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('domino_boletus_pairs', schema='events')
    op.drop_table('domino_boletus_data', schema='events')
    op.drop_table('trace_lottery_manual', schema='events')
    op.drop_table('domino_rounds_scale', schema='events')
    op.drop_table('domino_rounds_pairs', schema='events')
    op.drop_table('domino_boletus_position', schema='events')
    op.drop_table('referees', schema='events')
    op.drop_table('players', schema='events')
    op.drop_table('domino_tables_files', schema='events')
    op.drop_table('domino_boletus', schema='events')
    op.drop_table('domino_tables', schema='events')
    op.drop_table('domino_rounds', schema='events')
    op.drop_table('domino_categories', schema='events')
    op.drop_table('tourney', schema='events')
    # ### end Alembic commands ###
