"""add post tables

Revision ID: 6a6a7d1aa836
Revises: a046bd178a15
Create Date: 2023-03-01 11:57:23.471992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a6a7d1aa836'
down_revision = 'a046bd178a15'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='post'
    )
    op.create_table('post',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('image', sa.String(length=100), nullable=True),
    sa.Column('post_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_date', sa.Date(), nullable=False),
    sa.Column('publication_date', sa.Date(), nullable=False),
    sa.Column('expire_date', sa.Date(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('updated_date', sa.Date(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['enterprise.users.username'], ),
    sa.ForeignKeyConstraint(['post_type'], ['post.post_type.name'], ),
    sa.ForeignKeyConstraint(['status_id'], ['resources.entities_status.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['enterprise.users.username'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='post'
    )
    op.create_table('post_comments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('post_id', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['enterprise.users.username'], ),
    sa.ForeignKeyConstraint(['post_id'], ['post.post.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='post'
    )
    op.create_table('post_likes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('post_id', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['enterprise.users.username'], ),
    sa.ForeignKeyConstraint(['post_id'], ['post.post.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='post'
    )
    op.create_table('post_shares',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('post_id', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['enterprise.users.username'], ),
    sa.ForeignKeyConstraint(['post_id'], ['post.post.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='post'
    )
    op.create_table('post_shares_users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('share_id', sa.String(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['share_id'], ['post.post_shares.id'], ),
    sa.ForeignKeyConstraint(['user_name'], ['enterprise.users.username'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='post'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_shares_users', schema='post')
    op.drop_table('post_shares', schema='post')
    op.drop_table('post_likes', schema='post')
    op.drop_table('post_comments', schema='post')
    op.drop_table('post', schema='post')
    op.drop_table('post_type', schema='post')
    # ### end Alembic commands ###

# insert de tipos de post
# INSERT INTO post.post_type(name, description, created_by, created_date)
# 	   VALUES ('APP', 'Sitio Web Domino', 'foo', '2023-03-01');
# INSERT INTO post.post_type(name, description, created_by, created_date)
# 	   VALUES ('EVENT', 'Eventos', 'foo', '2023-03-01');
# INSERT INTO post.post_type(name, description, created_by, created_date)
# 	   VALUES ('TOURNEY', 'Torneos', 'foo', '2023-03-01');
# INSERT INTO post.post_type(name, description, created_by, created_date)
# 	   VALUES ('PLAYERS', 'Jugadores', 'foo', '2023-03-01');
# INSERT INTO post.post_type(name, description, created_by, created_date)
# 	   VALUES ('PAIRS', 'Parejas', 'foo', '2023-03-01');
# INSERT INTO post.post_type(name, description, created_by, created_date)
# 	   VALUES ('ROUND', 'Rondas', 'foo', '2023-03-01');
# INSERT INTO post.post_type(name, description, created_by, created_date)
# 	   VALUES ('TABLES', 'Mesas', 'foo', '2023-03-01');
# INSERT INTO post.post_type(name, description, created_by, created_date)
# 	   VALUES ('DATA', 'Partidos', 'foo', '2023-03-01');
# INSERT INTO post.post_type(name, description, created_by, created_date)
# 	   VALUES ('REFEREES', 'Arbitros', 'foo', '2023-03-01');