"""add categories table

Revision ID: 7364a0a54759
Revises: 63f83f2a95c6
Create Date: 2024-01-21 16:09:11.178478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7364a0a54759'
down_revision = '63f83f2a95c6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events_levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description'),
    sa.UniqueConstraint('level'),
    schema='resources'
    )
    op.create_table('events_scopes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description'),
    sa.UniqueConstraint('scope'),
    schema='resources'
    )
    op.create_table('player_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('value_k', sa.Float(), nullable=False),
    sa.Column('begin_elo', sa.Float(), nullable=False),
    sa.Column('end_elo', sa.Float(), nullable=False),
    sa.Column('width', sa.Float(), nullable=False),
    sa.Column('scope', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['scope'], ['resources.events_scopes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='resources'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_categories', schema='resources')
    op.drop_table('events_scopes', schema='resources')
    op.drop_table('events_levels', schema='resources')
    # ### end Alembic commands ###
