"""add table profile pair 

Revision ID: 77f7ae277e28
Revises: 7542111ec876
Create Date: 2023-07-10 08:57:16.715709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77f7ae277e28'
down_revision = '7542111ec876'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile_pair_player',
    sa.Column('profile_id', sa.String(), nullable=False),
    sa.Column('level', sa.String(length=60), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=False),
    sa.Column('updated_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['enterprise.profile_member.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['enterprise.users.username'], ),
    sa.PrimaryKeyConstraint('profile_id'),
    schema='enterprise'
    )
    op.create_table('profile_referee',
    sa.Column('profile_id', sa.String(), nullable=False),
    sa.Column('level', sa.String(length=60), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=False),
    sa.Column('updated_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['enterprise.profile_member.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['enterprise.users.username'], ),
    sa.PrimaryKeyConstraint('profile_id'),
    schema='enterprise'
    )
    op.create_table('profile_team_player',
    sa.Column('profile_id', sa.String(), nullable=False),
    sa.Column('level', sa.String(length=60), nullable=True),
    sa.Column('amount_members', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=False),
    sa.Column('updated_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['enterprise.profile_member.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['enterprise.users.username'], ),
    sa.PrimaryKeyConstraint('profile_id'),
    schema='enterprise'
    )
    

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile_team_player', schema='enterprise')
    op.drop_table('profile_referee', schema='enterprise')
    op.drop_table('profile_pair_player', schema='enterprise')
    