"""add ciudad table

Revision ID: 89e989fe5513
Revises: 8c8d5337668e
Create Date: 2023-01-10 19:53:40.198371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89e989fe5513'
down_revision = '8c8d5337668e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ciudad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('pais_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['pais_id'], ['configuracion.pais.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='configuracion'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ciudad', schema='configuracion')
    # ### end Alembic commands ###
