"""add status table 

Revision ID: 97069641de26
Revises: 0653057ebf69
Create Date: 2023-02-18 17:21:08.353020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97069641de26'
down_revision = '0653057ebf69'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entities_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='resources'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entities_status', schema='resources')
    # ### end Alembic commands ###
