"""add tourney tables

Revision ID: a046bd178a15
Revises: a32f63656c7f
Create Date: 2023-02-20 16:57:59.127370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a046bd178a15'
down_revision = 'a32f63656c7f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tourney',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('modality', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('close_date', sa.Date(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=100), nullable=True),
    sa.Column('manage_id', sa.String(), nullable=False),
    sa.Column('players_number', sa.Integer(), nullable=True),
    sa.Column('referees_number', sa.Integer(), nullable=True),
    sa.Column('tables_number', sa.Integer(), nullable=True),
    sa.Column('round_number', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_date', sa.Date(), nullable=False),
    sa.Column('updated_date', sa.Date(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['enterprise.users.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.events.id'], ),
    sa.ForeignKeyConstraint(['manage_id'], ['enterprise.users.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['resources.entities_status.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['enterprise.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='events'
    )
    op.create_table('gamerules',
    sa.Column('tourney_id', sa.String(), nullable=False),
    sa.Column('amount_points', sa.Integer(), nullable=True),
    sa.Column('amount_time', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tourney_id'], ['events.tourney.id'], ),
    sa.PrimaryKeyConstraint('tourney_id'),
    schema='events'
    )
    op.create_table('players',
    sa.Column('tourney_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('nivel', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['tourney_id'], ['events.tourney.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['enterprise.users.id'], ),
    sa.PrimaryKeyConstraint('tourney_id', 'user_id'),
    schema='events'
    )
    op.create_table('referees',
    sa.Column('tourney_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['tourney_id'], ['events.tourney.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['enterprise.users.id'], ),
    sa.PrimaryKeyConstraint('tourney_id', 'user_id'),
    schema='events'
    )
    op.create_table('sponsors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tourney_id', sa.String(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['tourney_id'], ['events.tourney.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='events'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sponsors', schema='events')
    op.drop_table('referees', schema='events')
    op.drop_table('players', schema='events')
    op.drop_table('gamerules', schema='events')
    op.drop_table('tourney', schema='events')
    # ### end Alembic commands ###
