"""add dom_categories table

Revision ID: afda3624e06a
Revises: 175a3c413c48
Create Date: 2023-11-13 12:02:45.511064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afda3624e06a'
down_revision = '175a3c413c48'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domino_categories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tourney_id', sa.String(), nullable=False),
    sa.Column('category_number', sa.String(length=100), nullable=False),
    sa.Column('position_number', sa.Integer(), nullable=False),
    sa.Column('elo_min', sa.Float(), nullable=False),
    sa.Column('elo_max', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['tourney_id'], ['events.tourney.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='events'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('domino_categories', schema='events')
    # ### end Alembic commands ###
