"""add post tables modify

Revision ID: ba374531ec5c
Revises: 1026a4342099
Create Date: 2023-03-23 09:34:41.630843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba374531ec5c'
down_revision = '1026a4342099'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_followers',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('user_follow', sa.String(length=50), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('username', 'user_follow'),
    schema='enterprise'
    )
    op.create_table('post',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['enterprise.users.username'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['enterprise.users.username'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='post'
    )
    op.create_table('post_comments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('post_id', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['enterprise.users.username'], ),
    sa.ForeignKeyConstraint(['post_id'], ['post.post.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='post'
    )
    op.create_table('post_files',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('post_id', sa.String(), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.post.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='post'
    )
    op.create_table('post_likes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('post_id', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['enterprise.users.username'], ),
    sa.ForeignKeyConstraint(['post_id'], ['post.post.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='post'
    )
    op.create_table('comment_comments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('comment_id', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['post.post_comments.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['enterprise.users.username'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='post'
    )
    op.create_table('comment_likes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('comment_id', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['post.post_comments.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['enterprise.users.username'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='post'
    )
    
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment_likes', schema='post')
    op.drop_table('comment_comments', schema='post')
    op.drop_table('post_likes', schema='post')
    op.drop_table('post_files', schema='post')
    op.drop_table('post_comments', schema='post')
    op.drop_table('user_followers', schema='enterprise')
    # ### end Alembic commands ###
