"""add domino boletus posi table

Revision ID: c33521396e2c
Revises: 34e5fbf2db14
Create Date: 2023-10-15 19:58:22.434416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c33521396e2c'
down_revision = '34e5fbf2db14'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domino_boletus_position',
    sa.Column('boletus_id', sa.String(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('single_profile_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['boletus_id'], ['events.domino_boletus.id'], ),
    sa.PrimaryKeyConstraint('boletus_id', 'position_id'),
    schema='events'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('domino_boletus_position', schema='events')
    # ### end Alembic commands ###
