"""add package table

Revision ID: c818d57bbd36
Revises: 97069641de26
Create Date: 2023-02-18 20:31:05.593436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c818d57bbd36'
down_revision = '97069641de26'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('packages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('number_individual_tourney', sa.Integer(), nullable=True),
    sa.Column('number_pairs_tourney', sa.Integer(), nullable=True),
    sa.Column('number_team_tourney', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('created_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='resources'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('packages', schema='resources')
    # ### end Alembic commands ###
