"""add setting table

Revision ID: d444dc3aac5d
Revises: 3e587f090574
Create Date: 2023-10-04 00:39:18.037217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd444dc3aac5d'
down_revision = '3e587f090574'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('setting_tourney',
    sa.Column('tourney_id', sa.String(), nullable=False),
    sa.Column('amount_tables', sa.Integer(), nullable=False),
    sa.Column('amount_smart_tables', sa.Integer(), nullable=False),
    sa.Column('amount_bonus_tables', sa.Integer(), nullable=False),
    sa.Column('amount_bonus_points', sa.Integer(), nullable=False),
    sa.Column('number_bonus_round', sa.Integer(), nullable=False),
    sa.Column('image', sa.Text(), nullable=True),
    sa.Column('amount_rounds', sa.Integer(), nullable=False),
    sa.Column('number_points_to_win', sa.Integer(), nullable=False),
    sa.Column('time_to_win', sa.Integer(), nullable=False),
    sa.Column('game_system', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['tourney_id'], ['events.tourney.id'], ),
    sa.PrimaryKeyConstraint('tourney_id'),
    schema='events')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('setting_tourney', schema='events')
        # ### end Alembic commands ###
