"""add user profile table

Revision ID: da450e988f37
Revises: 7ed1206a4e9e
Create Date: 2023-06-07 06:10:10.163647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da450e988f37'
down_revision = '7ed1206a4e9e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member_profile',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('modality', sa.String(length=50), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=True, comment='City to which the player belongs'),
    sa.Column('photo', sa.String(length=255), nullable=True),
    sa.Column('elo', sa.Integer(), nullable=True),
    sa.Column('ranking', sa.String(length=2), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_date', sa.Date(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=False),
    sa.Column('updated_date', sa.Date(), nullable=False),
    sa.Column('is_ready', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['resources.city.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['enterprise.users.username'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['enterprise.users.username'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='enterprise'
    )
    op.create_table('member_users',
    sa.Column('profile_id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('is_principal', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['enterprise.users.username'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['enterprise.member_profile.id'], ),
    sa.ForeignKeyConstraint(['username'], ['enterprise.users.username'], ),
    sa.PrimaryKeyConstraint('profile_id', 'username'),
    schema='enterprise'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('member_users', schema='enterprise')
    op.drop_table('member_profile', schema='enterprise')
    # ### end Alembic commands ###
